### ISSUE TITLE
Add support for VirtualNetwork

### ISSUE THREAD

**Issue by hasheddan** [hasheddan/stack-packet-demo#15]
### What problem are you facing?

`crossplane-provider-packet` does not currently support provisioning virtual networks on Packet.

### How could the Packet Crossplane Provider help solve your problem?

Add `v1alpha1` support for `VirtualNetwork` in the `vlan.packet.crossplane.io` group.

**Comment by displague** [comment]
The `VirtualNetwork` name maps well to Packet API endpoint: https://www.packet.com/developers/api/vlans/#vlans-createVirtualNetwork

`VLAN` is also an option, which aligns with the Terraform resource name (a non-goal): https://www.terraform.io/docs/providers/packet/r/vlan.html#argument-reference
