### ISSUE TITLE
Update tooling URLs to packethost org

### ISSUE THREAD

**Issue by hasheddan** [hasheddan/stack-packet-demo#3]
There are a number of places in the build tooling that use `github.com/hasheddan/stack-packet` as the repo URL (i.e. [here](https://github.com/packethost/stack-packet/blob/d6ae70f63691c5dee5474f76a8861133bcb23446/go.mod#L1)). This should be updated to `github.com/packethost/stack-packet`.

**Comment by jasmingacic** [comment]
@hasheddan this seems to be already done.

**Comment by hasheddan** [comment]
@jasmingacic I am still seeing links like the ones mentioned above in multiple locations:

https://github.com/packethost/stack-packet/blob/d6ae70f63691c5dee5474f76a8861133bcb23446/go.mod#L1

https://github.com/packethost/stack-packet/blob/d6ae70f63691c5dee5474f76a8861133bcb23446/Makefile#L5

I should be able to close this issue out today though!

**Comment by jasmingacic** [comment]
Understood
