### ISSUE TITLE
Prepare for Crossplane Certification

### ISSUE THREAD

**Issue by displague** [hasheddan/stack-packet-demo#56]
### What problem are you facing?

This provider should become a Crossplane Certified provider:
* https://github.com/cncf/crossplane-conformance/issues/3
* https://github.com/cncf/crossplane-conformance#crossplane-conformance
* https://github.com/cncf/crossplane-conformance/blob/main/instructions.md#how-to-submit-conformance-results

### How could the Equinix Metal Crossplane Provider help solve your problem?

* [x] Update the Provider to Crossplane 1.2
* [x] Implement an XRD?
* [x] ... (check for any other details not yet added to the conformance guidelines)

**Comment by negz** [comment]
FWIW no need to implement an XRD or anything. I suspect there's a good chance you're conformant at the moment if the provider works with Crossplane 1.2.

**Comment by displague** [comment]
Closing this 'preparatory' issue as the conformance submission has been made and all tests are passing using the following composition: https://github.com/cncf/crossplane-conformance/pull/22/files#diff-21d692ae5f5d0069c68cd54654e79d61dfc36eda5a7858cb681a7f772def70da
